#! /usr/bin/env python3

# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
#  NVIDIA CORPORATION and its licensors retain all intellectual property
#  and proprietary rights in and to this software, related documentation
#  and any modifications thereto.  Any use, reproduction, disclosure or
#  distribution of this software and related documentation without an express
#  license agreement from NVIDIA CORPORATION is strictly prohibited.

"""
A FPGA alert spec2code tool for device monitor & eventing support, ver=0.1
"""

import argparse
import csv
import os

FPGA_REGTBL_CONF_NAME = "fpga_regtbl_platform.conf"

fpga_redfish_event_templ = """
    {{
      "event": "{dev_name_pattern} {evt_name} Abnormal State Change",
      "device_type": "{dev_name_pattern}",
      "error_id": "{error_id}",
      "category": [
        "{evt_category}"
      ],
      "event_trigger": {{
        "type": "DBUS",
        "object": "/xyz/openbmc_project/GpioStatusHandler",
        "interface": "xyz.openbmc_project.GpioStatus",
        "property": "{alert_gpio}",
        "check": {{
          "equal": "false"
        }}
      }},
      "accessor": {{
        "type": "CMDLINE",
        "executable": "{regtbl_tool}",
        "arguments": "{reg_name} {dev_id}",
        "check": {{
          "equal": "1"
        }}
      }},
      "severity": "{evt_severity}",
      "resolution": "{evt_resolution}",
      "trigger_count": 0,
      "event_counter_reset": {{
        "type": "",
        "metadata": ""
      }},
      "redfish": {{
        "message_id": "ResourceEvent.1.0.ResourceErrorsDetected",
        "origin_of_condition": "{evt_ooc}",
        "message_args": {{
          "patterns": [
            "{dev_name_pattern} {evt_name}",
            "Abnormal State Change"
          ],
          "parameters": []
        }}
      }},
      "telemetries": [],
      "action": "",
      "value_as_count": false,
      "description": "{descr}"
    }},
"""

fpga_regtbl_conf_templ = """#######################################################################
### WARNING!! Auto-generated file! All modification will be lost! ###
#######################################################################

# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
#  NVIDIA CORPORATION and its licensors retain all intellectual property
#  and proprietary rights in and to this software, related documentation
#  and any modifications thereto.  Any use, reproduction, disclosure or
#  distribution of this software and related documentation without an express
#  license agreement from NVIDIA CORPORATION is strictly prohibited.

# This is an auto-generated file that compiles platform specific data required
# for the fpga_regtbl utility to properly determine the cause of an interrupt
# and subsequently clear said interrupt if possible. fpga_regtbl is expected
# to source the contents of this file.

REGTBL_BUS={regtbl_bus}
REGTBL_SADDR={regtbl_saddr}
REGTBL_PAGES={regtbl_pages}

# Format,
#   reg_name, byte_off, byte_len, bit_mask(hex), byte_range, bit_range
# e.g.,
#   MOD_VR_FAULT,384,11,0x00fffff0,128-131,4-23
#   GPU_THERM_OVERT_INT,75,2,0x1,25,1
#
REG_LIST="
{reg_list}
"

# Format,
#   reg_name, dev_id, clr_cmd
# e.g.,
#   MOD_PRSNT_INT,0,busctl call xyz.openbmc_project.GpuMgr /xyz/openbmc_project/GpuMgr xyz.openbmc_project.GpuMgr.Server PassthroughFpga iyyyau 0 0xB7 0x00 0x01 0
#   MOD_PRSNT_INT,1,busctl call xyz.openbmc_project.GpuMgr /xyz/openbmc_project/GpuMgr xyz.openbmc_project.GpuMgr.Server PassthroughFpga iyyyau 0 0xB7 0x01 0x01 0
#
CLEAR_CMD_LIST="
{clear_cmd_list}
"
"""

# [7:0] => 0xff, or 5 => 0x20
# and also return the corrected bit range in format of,
#   min-max
def bitrange_to_bitmask(bit_range):
    bits_arr = bit_range.split(':')
    if len(bits_arr) == 2:
        bit_min = int(bits_arr[1])
        bit_max = int(bits_arr[0])
        bitrange = str(bit_min) + '-' + str(bit_max)
    elif len(bits_arr) == 1:
        bit_min = bit_max = int(bits_arr[0])
        bitrange = str(bit_min)
    else:
        return 1, 0

    bits = 0
    for i in range(bit_min, bit_max+1):
        bits += 1 << i

    return 0, bits, bitrange

class FpgaRegtbl:
    def __init__(self, regtbl_bus, regtbl_addr, regtbl_pages, regtbl_file, intr_clr_cmds):
        # csv.DictReader is a lazy dict, need to reload its content from
        # file after each iteration. So only cache filename here for reloading.
        self._regtbl_bus = regtbl_bus
        self._regtbl_addr = regtbl_addr
        self._regtbl_pages = regtbl_pages
        self._regtbl_file = regtbl_file
        self._intr_clr_cmds = intr_clr_cmds

    # return defvalue/bits lowest offset of the specified reg, throw exceptions if reg not exist.
    def get_reg_defvalue(self, reg_name):
        with open(self._regtbl_file, "r", encoding='utf-8-sig') as f:
            regtbl = csv.DictReader(f)
            for row in regtbl:
                if row["Reg Name"].split('[')[0] == reg_name:
                    return 0, row["Default"], row["Bits"].split(':')[-1]
        return 1, "", ""

    # simply name conversion in strings, no guarantee of existence.
    def intr_to_gpi_reg_name(self, intr_name):
        suffix = "_INT"
        if intr_name.endswith(suffix):
            return intr_name[:-len(suffix)] # Remove the tailing "_INT" for GPI reg name
        else:
            return ""

    # simply name conversion in strings, no guarantee of existence.
    def gpi_to_mask_reg_name(self, gpi_name):
        return gpi_name + "_MASK"

    # simply name conversion in strings, no guarantee of existence.
    def intr_to_mask_reg_name(self, intr_name, long_name = 0):
        if long_name == 0:
            return intr_name + "_MASK"
        else:
            return self.gpi_to_mask_reg_name(self.intr_to_gpi_reg_name(intr_name))

    # simply name conversion in strings, no guarantee of existence.
    def intr_to_gpio_name(self, intr):
        if intr == "T":
            return "THERM_OVERT"
        else:
            return "I2C" + intr + "_ALERT"

    def get_intr_mask_info(self, intr_name):
        for long_name in [0, 1]:
            # get interrupt mask reg
            mask_name = self.intr_to_mask_reg_name(intr_name, long_name)

            # get interrupt mask default value
            rc, mask_value, bits = self.get_reg_defvalue(mask_name)
            if rc == 0:
                mask_value = int(mask_value, 16)
                mask_value <<= int(bits, 10)
                return 0, mask_name, mask_value
        else:
            return rc, "", ""


    def get_intr_list(self, hmc_or_bmc):
        col = "Int for HMC" if hmc_or_bmc == "hmc" else "Int for BMC"
        with open(self._regtbl_file, "r", encoding='utf-8-sig') as f:
            regtbl = csv.DictReader(f)
            print('Interrupt,ByteRange,Bitmask,IntrMask,IntrMaskValue,AlertGPIO')
            for row in regtbl:
                intr_gpio = row[col]
                if intr_gpio == "":
                    continue

                # get gpio name for the interrupt
                gpio = self.intr_to_gpio_name(intr_gpio)

                # get interrupt name
                intr_name = row["Reg Name"].split('[')[0]  # e.g. MOD_VR_FAULT_INT[7:0] => MOD_VR_FAULT_INT

                # get intr mask name and def_value
                rc, mask_name, intr_mask = self.get_intr_mask_info(intr_name)
                if rc != 0:
                    print("[E] Can't find mask for intr: ", intr_name)
                    continue

                # get byte range
                byte = str(int(row["Address Start"], 16))  # convert regtbl hex to decimal string
                if row["Address End"] != "":
                    byte = byte + '-' + str(int(row["Address End"], 16))

                # get bit range
                bits = row["Bits"]

                # get bitmask
                rc, bitmask, bit_range = bitrange_to_bitmask(bits)
                if rc != 0:
                    print("[E] Unsupported bits format: ", bits)
                    continue

                # mask off the interrupts per regtbl
                bitmask = bitmask ^ intr_mask # (intr_mask == 1) => no intr reported

                print('{0},{1},{2},{3},{4},{5}'.format(intr_name, byte, hex(bitmask), mask_name, hex(intr_mask), gpio))

    def to_event_info_json(self):
        col = "Int for HMC"
        with open(self._filename, "r", encoding='utf-8-sig') as f:
            # # Skip lines with only commas
            # line = next(f)
            # while set(line.strip()) <= {',', ' '}:
            #     line = next(f)

            # # Now 'line' holds the first non-empty line
            # # We put it back into the file's iterator to include it in DictReader
            # f.seek(f.tell() - len(line))

            regtbl = csv.DictReader(f)

            output = '{\n  "Device": ['
            for row in regtbl:
                intr_gpio = row[col]
                if intr_gpio == "":
                    continue

                event_name = reg_name = row["Reg Name"].split('[')[0]  # e.g. MOD_VR_FAULT_INT[7:0] => MOD_VR_FAULT_INT
                event_name = '_'.join(event_name.split('_')[1:])
                dev_id = "[0-1]"
                error_id = reg_name + "-ERROR"
                evt_category = "erot-control"
                alert_gpio = self.intr_to_gpio_name(intr_gpio)
                regtbl_tool = FPGA_REGTBL_TOOL_NAME
                evt_severity = "Critical"
                evt_resolution = "AC cycle the system. If problem persists, collect all dumps per troubleshooting guide, isolate the system and evaluate for RMA."
                evt_ooc = "POWER"
                dev_name_pattern = reg_name.split('_')[0]
                descr = "FPGA interrupt " + reg_name + " happens."

                output += fpga_redfish_event_templ.format(
                    evt_name = event_name,
                    error_id = error_id,
                    evt_category = evt_category,
                    alert_gpio = alert_gpio,
                    regtbl_tool = regtbl_tool,
                    reg_name = reg_name,
                    dev_id = dev_id,
                    evt_severity = evt_severity,
                    evt_ooc = evt_ooc,
                    evt_resolution = evt_resolution,
                    dev_name_pattern = dev_name_pattern,
                    descr = descr
                    )

            output = output[:-2] # to remove the tailing ',' for JSON syntax.
            output += "\n  ]\n}\n"
            print(output)

    def get_reg_list(self, new_format=False):
        reg_info_list = ""
        with open(self._regtbl_file, "r", encoding='utf-8') as f:
            regtbl = csv.DictReader(f)

            for row in regtbl:
                intr_gpio = row["Int for HMC"].strip()
                if intr_gpio == "":
                    continue

                # get gpio name for the interrupt
                gpio = self.intr_to_gpio_name(intr_gpio)

                # get interrupt name
                intr_name = row["Reg Name"].strip().split('[')[0]  # e.g. MOD_VR_FAULT[7:0] => MOD_VR_FAULT

                if intr_name == "RSVD":
                    continue

                # get intr mask name and def_value
                rc, mask_name, intr_mask = self.get_intr_mask_info(intr_name)
                if rc != 0:
                    print("[W] Can't find mask for intr: ", intr_name)
                    intr_mask = 0

                # format byte range in "min(dec)-max(dec)"
                byte_min=int(row["Address Start"].strip(), 16)
                byte_max=byte_min

                byte_range = str(byte_min)

                if row["Address End"].strip() != "":
                    byte_max = int(row["Address End"].strip(), 16)
                    byte_range = byte_range + '-' + str(byte_max)


                # convert byte range to shell string manipulate expression for parsing i2ctransfer outputs.
                # output example (data between []):
                # pos:   0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
                # data: [78 84 00 59 00 00 08 01 00 00 00 40 30 1e 04]
                byte_off = byte_min * 3
                byte_len = 2 + (byte_max - byte_min) * 3

                # convert bit range to bit mask
                # get bit range
                bits = row["Bits"].strip()

                # get bitmask
                rc, bitmask, bit_range = bitrange_to_bitmask(bits)
                if rc != 0:
                    print("[E] Unsupported bits format: ", bits)
                    continue

                # mask off the interrupts per regtbl
                print("[D]", intr_name, "bitmask:", hex(bitmask), "intr_mask:", hex(intr_mask))
                bitmask = bitmask ^ intr_mask # (intr_mask == 1) => no intr reported
                prefix = "#" if bitmask == 0 else ""
                bitmask = hex(bitmask)

                # This format needs to be aligned with the 'fpga_regtbl' logic
                if new_format:
                    reg_info_list += '{0}{1}_{2}={3}\n'.format(prefix, intr_name, 'byte_off', byte_off)
                    reg_info_list += '{0}{1}_{2}={3}\n'.format(prefix, intr_name, 'byte_len', byte_len)
                    reg_info_list += '{0}{1}_{2}={3}\n'.format(prefix, intr_name, 'bitmask', bitmask)
                    reg_info_list += '{0}{1}_{2}={3}\n'.format(prefix, intr_name, 'byte_range', byte_range)
                    reg_info_list += '{0}{1}_{2}={3}\n'.format(prefix, intr_name, 'bit_range', bit_range)
                else:
                    reg_info_list += '{0}{1},{2},{3},{4},{5},{6}\n'.format(prefix,
                        intr_name, byte_off, byte_len, bitmask, byte_range, bit_range)

        return reg_info_list

    def get_intr_clr_cmds(self):
        intr_clr_cmds = ""
        if not os.path.exists(self._intr_clr_cmds):
            return ""

        with open(self._intr_clr_cmds, "r") as f:
            clr_cmd_list = csv.DictReader(f)

            for row in clr_cmd_list:
                reg_name = row["Reg Name"]
                if reg_name == "":
                    continue
                dev_id = row["Device ID"]
                clr_cmd = row["Interrupt Clearing Command"]

                # This format needs to be aligned with the 'fpga_regtbl' logic
                intr_clr_cmds += '{0},{1},{2}\n'.format(reg_name, dev_id, clr_cmd)

        return intr_clr_cmds

    def to_regtbl_platform_conf(self, conf_file_name):
        reg_info_list = self.get_reg_list()
        intr_clr_cmd_list = self.get_intr_clr_cmds()
        output_data = fpga_regtbl_conf_templ.format(
            reg_list = reg_info_list,
            clear_cmd_list = intr_clr_cmd_list,
            regtbl_bus = self._regtbl_bus,
            regtbl_saddr = self._regtbl_addr,
            regtbl_pages = self._regtbl_pages)

        if conf_file_name != "":
            try:
                with open(conf_file_name, "w+") as output:
                    output.write(output_data)
                print("[I] The FPGA regtbl platform config is generated at [", conf_file_name, "].")
                return 0
            except:
                print("[E] Failed to generate the FPGA regtbl data!")
                return 1
        else:
            print(conf_file_name)
            return 0

    def to_error_catalog(self, error_catalog = ""):
        with open(self._filename, "a+") as f:
            # Skip lines with only commas
            line = next(f)
            while set(line.strip()) <= {',', ' '}:
                line = next(f)

            # Now 'line' holds the first non-empty line
            # We put it back into the file's iterator to include it in DictReader
            f.seek(f.tell() - len(line))

            regtbl = csv.DictReader(f)
            reg_info_list = ""
            for row in regtbl:
                if row[col] == "":
                    continue

                intr_name = row["Reg Name"].split('[')[0]  # e.g. MOD_VR_FAULT_INT[7:0] => MOD_VR_FAULT_INT

                # get intr mask name and def_value
                rc, mask_name, intr_mask = self.get_intr_mask_info(intr_name)
                if rc != 0:
                    print("[E] Can't find mask for intr: ", intr_name)
                    continue

                # get byte range
                byte = str(int(row["Address Start"], 16))  # convert regtbl hex to decimal string
                if row["Address End"] != "":
                    byte = byte + '-' + str(int(row["Address End"], 16))

                # get bit range
                bits = row["Bits"]

                # get bitmask
                rc, bitmask, bit_range = bitrange_to_bitmask(bits)
                if rc != 0:
                    print("[E] Unsupported bits format: ", bits)
                    continue

                # mask off the interrupts per regtbl
                bitmask = bitmask ^ intr_mask # (intr_mask == 1) => no intr reported

                print('{0},{1},{2},{3},{4}'.format(intr_name, byte, hex(bitmask), mask_name, hex(intr_mask)))

def convert_xlsx_to_csv(xlsx_file, sheet_name):
    import pandas as pd

    # Read the specified sheet from the Excel file
    df = pd.read_excel(xlsx_file, header=4, sheet_name=sheet_name)

    # Make the csv file path.
    csv_file = "/tmp/" + os.path.splitext(os.path.basename(xlsx_file))[0] + "_" + sheet_name.replace(" ", "_") + ".csv"

    # Convert the DataFrame to a CSV file
    df.to_csv(csv_file, index = False, encoding = 'utf-8')

    return csv_file

help_example="\
Examples,\n \
  For GB200 NVL fpga_regtbl_platform.conf,\n \
  ./fpga_alert_spec2code bianca_regtbl_i2c_info_v1.xlsx \"\" 0x01 0x11 4 to_regtbl_platform_conf\n \
\n \
  fpga_regtbl_platform.conf will be generated in current folder.\n \
"

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=help_example
    )

    parser.add_argument(
        "regtbl_file",
        metavar="REGTBL_FILE",
        help="FPGA register table definition file in .xlsx format.")

    parser.add_argument(
        "intr_clr_cmds",
        metavar="INTR_CLR_CMDS",
        help="Interrupt clearing command definition file in .csv format.")

    parser.add_argument(
        "regtbl_i2c_bus",
        metavar="REGTBL_I2C_BUS",
        help="FPGA register table I2C bus.")

    parser.add_argument(
        "regtbl_i2c_addr",
        metavar="REGTBL_I2C_ADDR",
        help="FPGA register table I2C addr")

    parser.add_argument(
        "regtbl_pages",
        metavar="REGTBL_PAGES",
        help="Total number of FPGA register table pages")


    conv_method_help_msg = [method for method in dir(FpgaRegtbl) if method.startswith("to_")]

    parser.add_argument(
        "conv_method",
        metavar="conv_method",
        help="Specify how to convert the spec to code. Options:\n  " + "\n  ".join(conv_method_help_msg) + "\n")

    args = parser.parse_args()

    i2c_bus = args.regtbl_i2c_bus
    i2c_addr = args.regtbl_i2c_addr
    regtbl_pages = args.regtbl_pages
    regtbl_csv = convert_xlsx_to_csv(args.regtbl_file, "REGTBL")
    intr_clr_csv = args.intr_clr_cmds
    
    fpga_regtbl = FpgaRegtbl(i2c_bus, i2c_addr, regtbl_pages, regtbl_csv, intr_clr_csv)
    
    rc = 0
    
    if args.conv_method == "to_error_catalog":
        rc = fpga_regtbl.to_error_catalog()
    elif args.conv_method == "get_intr_list":
        rc = fpga_regtbl.get_intr_list("hmc")
    elif args.conv_method == "to_event_info_json":
        rc = fpga_regtbl.to_event_info_json()
    elif args.conv_method == "list_all_reg":
        rc = fpga_regtbl.get_reg_defvalue("not exist")
    elif args.conv_method == "to_regtbl_platform_conf":
        rc = fpga_regtbl.to_regtbl_platform_conf(FPGA_REGTBL_CONF_NAME)
    elif args.conv_method == "to_intr_varlist":
        rc = fpga_regtbl.get_reg_list(True)
    else:
        print("Wrong args: ", args.conv_method)
        rc = 1

    return rc

if __name__ == "__main__":
    main()
