#!/usr/bin/env bash

set -o pipefail

app_name=redfish_eventing_recipe_validator
app_ver=0.1

DEFUSR=nobody
DEFGRP=nogroup

get_realuser()
{
    local rusr;rusr=`logname 2>/dev/null`
    [ $? -ne 0 ] || [ -z "$rusr" ] && rusr=${LOGNAME}
    [ -z "$rusr" ] && rusr=${USER}
    [ -z "$rusr" ] && rusr=${DEFUSR}
    echo $rusr
}

get_realgroup() # (user)
{
    local usr=$1
    [ -z "$usr" ] && usr=${DEFUSR}
    if [ "${DEFUSR}" = "$usr" ]; then
        echo "${DEFGRP}"
        return 0
    fi
    local grp;grp=`groups "$usr" 2>/dev/null | cut -d' ' -f3`
    [ $? -ne 0 ] || [ -z "$grp" ] && grp=${DEFGRP}
    echo $grp
}

REALUSER=`get_realuser`
REALGROUP=`get_realgroup "${REALUSER}"`
LOGPATH=/tmp/${REALUSER}_${app_name}_$$
LOGTMP=tmp.log
LOGAPP=app.log
APPTMP=${LOGPATH}/${LOGTMP}
APPLOG=${LOGPATH}/${LOGAPP}

initlog()
{
    [ -d "${LOGPATH}" ] || mkdir -p "${LOGPATH}"
}

cleanup()
{
    [ -d "${LOGPATH}" ] || return
    rm -rf "${LOGPATH}"
    set +o pipefail
}

trap cleanup EXIT
initlog
###############################################################################

show_help()
{
    echo "A tool to validate Redfish Eventing Recipes, ver=$app_ver"
    echo "<usage>"
    echo "  $app_name"
    echo
}

# Format: event,recipe,key,condition,resolution
checklist="
GENERAL,bmcweb,EXTRA_OEMESON,nvidia-oem-properties=enabled
GENERAL,phosphor-logging,EXTRA_OEMESON,error_cap=300
GENERAL,phosphor-logging,EXTRA_OEMESON,error_info_cap=50
GENERAL,phosphor-logging,[file],phosphor-logging-namespace.json
GENERAL,phosphor-logging,[install],phosphor-logging-namespace.json


PLDMT2,pldm,EXTRA_OEMESON,pldm-type2=enabled
PLDMT2,pldm,EXTRA_OEMESON,libpldmresponder=enabled
PLDMT2,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,pldm

CPER,phosphor-debug-collector,[file],cper_dump.sh
CPER,phosphor-debug-collector,[install],cper_dump.sh
CPER,phosphor-debug-collector,EXTRA_OEMESON,faultlog-dump-extension=enabled
CPER,phosphor-debug-collector,EXTRA_OEMESON,nvidia-dumps-extension=enabled
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_PATH=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_MAX_SIZE=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_MIN_SPACE_REQD=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_TOTAL_SIZE=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_MAX_LIMIT=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_OBJPATH=
CPER,phosphor-debug-collector,EXTRA_OEMESON,FAULTLOG_DUMP_OBJ_ENTRY=
CPER,phosphor-debug-collector,RDEPENDS(.*),bash
CPER,phosphor-debug-collector,RDEPENDS(.*),nvidia-cperdecoder
CPER,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-cperdecoder

XID_SMBPBI,nvidia-xid-event-handler,[file],xid_devices.csv
XID_SMBPBI,nvidia-xid-event-handler,[install],xid_devices.csv
XID_SMBPBI,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-xid-event-handler

XID_NSM,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nsm

NSM_EVENT,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nsm

FPGA_ALERT,nvidia-monitor-eventing,[file],event_info.json
FPGA_ALERT,nvidia-monitor-eventing,[install],event_info.json
FPGA_ALERT,nvidia-monitor-eventing,[file],dat.json
FPGA_ALERT,nvidia-monitor-eventing,[install],dat.json
FPGA_ALERT,nvidia-monitor-eventing,[file],fpga_regtbl
FPGA_ALERT,nvidia-monitor-eventing,[install],fpga_regtbl
FPGA_ALERT,nvidia-monitor-eventing,[file],fpga_regtbl_platform.conf
FPGA_ALERT,nvidia-monitor-eventing,[install],fpga_regtbl_platform.conf
FPGA_ALERT,nvidia-gpio-status-handler,[file],gpio-config.json
FPGA_ALERT,nvidia-gpio-status-handler,[install],gpio-config.json
FPGA_ALERT,bmcweb,EXTRA_OEMESON,nvidia-oem-logservices=enabled
FPGA_ALERT,bmcweb,EXTRA_OEMESON,redfish-dbus-event=enabled
FPGA_ALERT,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-gpio-status-handler
FPGA_ALERT,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-monitor-eventing

TELM_BASED,nvidia-monitor-eventing,[file],event_info.json
TELM_BASED,nvidia-monitor-eventing,[install],event_info.json
TELM_BASED,nvidia-monitor-eventing,[file],dat.json
TELM_BASED,nvidia-monitor-eventing,[install],dat.json
TELM_BASED,bmcweb,EXTRA_OEMESON,nvidia-oem-logservices=enabled
TELM_BASED,bmcweb,EXTRA_OEMESON,redfish-dbus-event=enabled
TELM_BASED,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-monitor-eventing

DEVICE_HEALTH,bmcweb,EXTRA_OEMESON,nvidia-oem-device-status-from-file=enabled
DEVICE_HEALTH,bmcweb,EXTRA_OEMESON,health-rollup-alternative=disabled
DEVICE_HEALTH,bmcweb,EXTRA_OEMESON,platform-system-id=
DEVICE_HEALTH,bmcweb,EXTRA_OEMESON,nvidia-oem-properties=enabled
DEVICE_HEALTH,obmc-phosphor-image,OBMC_IMAGE_EXTRA_INSTALL,nvidia-monitor-eventing

"

msg_pass()
{
    echo -en "\033[1;32m$@\033[0m"
}

msg_fail()
{
    echo -en "\033[0;31m$@\033[0m"
}

main()
{
    echo "Checking..."
    local chk
    while read -r chk; do
        [ -z "${chk}" ] && continue
        [ "${chk:0:1}" == "#" ] && continue

        local evt=`echo $chk | cut -d',' -f1`
        local recipe=`echo $chk | cut -d',' -f2`
        local key=`echo $chk | cut -d',' -f3`
        local cond=`echo $chk | cut -d',' -f4`

        # Cache full recipe content to file if not exist.
        local tmp_recipe="${LOGPATH}/$recipe"
        [ -f "$tmp_recipe" ] || bitbake -e $recipe > $tmp_recipe

        local msg="$evt:$recipe:"

        # Hanlde special key cases
        if [ "$key" == "[file]" ]; then
            echo -n "${msg}exists?:$cond: "
            local f;f=`find tmp/work/*-openbmc-linux-gnueabi/$recipe/ -name "$cond" 2>/dev/null`
            [ -n "$f" ] && msg_pass "Yes" || msg_fail "No"
            echo
            continue
        fi

        if [ "$key" == "[grep -E]" ]; then
            echo -n "${msg}contains?:$cond: "
            cat $tmp_recipe | grep -E "$cond" &>/dev/null
            [ "$?" -eq 0 ] && msg_pass "Yes" || msg_fail "No"
            echo
            continue
        fi

        if [ "$key" == "[install]" ]; then
            echo -n "${msg}installed?:$cond: "
            cat $tmp_recipe | grep "$cond" | grep "\(SRC_URI\|install -m\)" &>/dev/null
            [ "$?" -eq 0 ] && msg_pass "Yes" || msg_fail "No"
            echo
            continue
        fi

        # Handle normal key cases

        # Cache key value in file if not exist.
        local tmp_key="${tmp_recipe}_${key}"
        [ -f "$tmp_key" ] || cat $tmp_recipe | grep -E "^${key}=" > $tmp_key

        echo -n "$msg$key:$cond: "
        local val;val=`cat $tmp_key | grep "$cond"`
        [ "$?" -eq 0 ] && msg_pass "Yes" || msg_fail "No"
        echo

    done <<< $checklist
}

## MAIN ##
main $@

